"""Canadian residential construction master checklist template."""

MASTER_TEMPLATE = {
    "Pre-Construction": {
        "Permits & Approvals": [
            ("Building permit obtained and posted on site", "VERIFY"),
            ("Zoning compliance confirmed", "VERIFY"),
            ("Lot grading plan approved", "VERIFY"),
            ("Development permit in place (if applicable)", "VERIFY"),
            ("Utility locate (Ontario One Call / BC One Call) completed", "PRIOR TO ORDER"),
            ("Site survey and staking completed", "VERIFY"),
            ("Tree removal permit (if applicable)", "VERIFY"),
            ("Erosion and sediment control plan in place", "ACTION"),
        ],
        "Site Preparation": [
            ("Site access and temporary road established", "ACTION"),
            ("Temporary power and water arranged", "PRIOR TO ORDER"),
            ("Portable toilet on site", "ACTION"),
            ("Material laydown area designated", "ACTION"),
            ("Construction signage posted", "ACTION"),
            ("Existing utilities marked and protected", "VERIFY"),
            ("Topsoil stripped and stockpiled", "ACTION"),
        ],
        "Pre-Construction Meeting": [
            ("Pre-construction meeting held with trades", "ACTION"),
            ("Construction schedule distributed", "INFORM CONTRACTOR"),
            ("Emergency contact list posted", "ACTION"),
            ("Scope of work reviewed with client", "CLIENT"),
        ],
    },
    "Foundation": {
        "Excavation": [
            ("Excavation depth matches engineered drawings", "VERIFY"),
            ("Soil bearing capacity confirmed (geotechnical report)", "VERIFY"),
            ("Dewatering system in place (if needed)", "ACTION"),
            ("Excavation walls stable / shored if required", "VERIFY"),
            ("Over-excavation areas backfilled with granular", "VERIFY"),
            ("Footing elevation matches benchmark", "VERIFY"),
        ],
        "Footings": [
            ("Footing dimensions per structural drawings", "VERIFY"),
            ("Rebar size, spacing, and placement verified", "VERIFY"),
            ("Rebar cover (75mm min) maintained with chairs", "VERIFY"),
            ("Keyway formed in top of footing", "VERIFY"),
            ("Concrete mix design approved (min 25 MPa)", "VERIFY"),
            ("Concrete slump test performed", "VERIFY"),
            ("Footing inspection by building inspector — passed", "VERIFY"),
            ("Step footings match grade change per drawings", "VERIFY"),
        ],
        "Foundation Walls": [
            ("Wall forms aligned, plumb, and braced", "VERIFY"),
            ("Wall thickness per drawings (min 8\" / 200mm)", "VERIFY"),
            ("Rebar placement in walls per structural plan", "VERIFY"),
            ("Window bucks and beam pockets placed", "VERIFY"),
            ("Snap ties and form hardware clean", "VERIFY"),
            ("Concrete pour completed — no honeycombing", "VERIFY"),
            ("Foundation wall inspection — passed", "VERIFY"),
            ("Form stripping done carefully, no damage", "ACTION"),
        ],
        "Waterproofing & Drainage": [
            ("Dampproofing / waterproofing membrane applied", "VERIFY"),
            ("Drainage mat (Delta-MS or equivalent) installed", "VERIFY"),
            ("Weeping tile installed at footing level", "VERIFY"),
            ("Weeping tile connected to sump pit or storm", "VERIFY"),
            ("Sump pit and lid installed", "VERIFY"),
            ("Granular backfill around foundation (clear stone)", "VERIFY"),
            ("Backfill completed in lifts, compacted", "ACTION"),
            ("Window wells installed (if applicable)", "VERIFY"),
        ],
        "Basement Slab": [
            ("Granular base compacted (min 150mm)", "VERIFY"),
            ("Vapour barrier (6 mil poly) installed, lapped and sealed", "VERIFY"),
            ("Under-slab insulation (if required by code)", "VERIFY"),
            ("Under-slab plumbing roughed in and tested", "PRIOR TO POUR"),
            ("Radon rough-in pipe installed (NBC requirement)", "VERIFY"),
            ("Slab reinforcement (mesh or rebar) in place", "VERIFY"),
            ("Slab thickness per drawing (min 75mm)", "VERIFY"),
            ("Control joints planned / saw-cut within 24 hrs", "ACTION"),
        ],
    },
    "Framing": {
        "Floor System": [
            ("Sill plate gasket / sill seal installed", "VERIFY"),
            ("Sill plate anchored (min 1/2\" bolts at 6' o.c.)", "VERIFY"),
            ("Floor joist size and spacing per plan", "VERIFY"),
            ("Engineered beams / LVLs match schedule", "VERIFY"),
            ("Joist hangers installed per manufacturer specs", "VERIFY"),
            ("Bridging / blocking installed", "VERIFY"),
            ("Subfloor glued and screwed (min 5/8\" T&G)", "VERIFY"),
            ("Floor openings framed for stairs, chases", "VERIFY"),
        ],
        "Wall Framing": [
            ("Wall layout matches architectural plans", "VERIFY"),
            ("Stud size and spacing (16\" o.c. typical)", "VERIFY"),
            ("Headers and cripples at all openings", "VERIFY"),
            ("Corner framing allows for insulation / drywall backing", "VERIFY"),
            ("Sheathing applied (OSB / plywood per code)", "VERIFY"),
            ("Nailing pattern per wind load requirements", "VERIFY"),
            ("All bearing walls aligned and continuous load path", "VERIFY"),
            ("Fire blocking installed at floor transitions", "VERIFY"),
            ("Plumb and straight — checked with level", "VERIFY"),
        ],
        "Roof Framing": [
            ("Truss layout matches engineered drawings", "VERIFY"),
            ("Truss bracing per engineer's notes", "VERIFY"),
            ("Fascia and soffit backing installed", "VERIFY"),
            ("Roof sheathing (min 3/8\" or per code) installed", "VERIFY"),
            ("H-clips installed between sheathing panels", "VERIFY"),
            ("Ridge beam / valley framing per plan", "VERIFY"),
            ("Attic access framed (min 22\" x 30\")", "VERIFY"),
            ("Roof ventilation — soffit + ridge calculation confirmed", "VERIFY"),
        ],
        "Windows & Exterior Doors": [
            ("Window sizes match schedule", "VERIFY"),
            ("Window installation per manufacturer specs", "VERIFY"),
            ("Sill pan flashing installed under windows", "VERIFY"),
            ("Self-adhering membrane at window/door rough openings", "VERIFY"),
            ("Exterior doors hung, plumb, and operational", "VERIFY"),
            ("Threshold sealed and flashed", "VERIFY"),
        ],
        "Framing Inspection": [
            ("All hold-downs and straps installed per engineer", "VERIFY"),
            ("Framing inspection by building inspector — passed", "VERIFY"),
            ("Deficiency list from inspection addressed", "ACTION"),
        ],
    },
    "Mechanical Rough-In": {
        "Electrical Rough-In": [
            ("Panel location per plan, backing installed", "VERIFY"),
            ("Wire gauge matches circuit load (14/2, 12/2, etc.)", "VERIFY"),
            ("Outlet heights: 12\" standard, 48\" countertop", "VERIFY"),
            ("Switch heights: 48\" standard", "VERIFY"),
            ("GFCI circuits in kitchen, bath, exterior, garage", "VERIFY"),
            ("AFCI protection on bedroom circuits (code req)", "VERIFY"),
            ("Smoke / CO detector locations per code", "VERIFY"),
            ("Exterior outlet locations (front, rear, deck)", "VERIFY"),
            ("Dedicated circuits: stove, dryer, A/C, furnace", "VERIFY"),
            ("Low voltage rough-in: data, TV, speaker", "ACTION"),
            ("EV charger rough-in (if specified)", "CLIENT"),
            ("Electrical inspection — passed", "VERIFY"),
        ],
        "Plumbing Rough-In": [
            ("Drain/waste/vent layout per plan", "VERIFY"),
            ("Pipe sizes match code requirements", "VERIFY"),
            ("Water supply lines: PEX or copper per spec", "VERIFY"),
            ("Shower/tub valves at correct height", "VERIFY"),
            ("Toilet flange location and height verified", "VERIFY"),
            ("Hose bibs located per plan (frost-proof)", "VERIFY"),
            ("Water heater location and venting planned", "VERIFY"),
            ("Pressure test completed (hold 30 min min)", "VERIFY"),
            ("Backflow prevention device installed", "VERIFY"),
            ("Plumbing inspection — passed", "VERIFY"),
        ],
        "HVAC Rough-In": [
            ("Duct layout per mechanical drawings", "VERIFY"),
            ("Supply and return register locations marked", "VERIFY"),
            ("Furnace location and clearances per code", "VERIFY"),
            ("HRV/ERV location and ducting confirmed", "VERIFY"),
            ("Bathroom exhaust fans ducted to exterior", "VERIFY"),
            ("Range hood duct to exterior (no recirculating)", "VERIFY"),
            ("Dryer vent to exterior (rigid or semi-rigid)", "VERIFY"),
            ("Combustion air supply provided (if gas appliances)", "VERIFY"),
            ("HVAC inspection — passed", "VERIFY"),
        ],
        "Fire Protection": [
            ("Smoke detectors wired: every bedroom + hallway + floor", "VERIFY"),
            ("CO detectors wired: near sleeping areas + furnace", "VERIFY"),
            ("Fire separations maintained (garage, utility)", "VERIFY"),
            ("Firestop caulking at all penetrations through rated assemblies", "ACTION"),
        ],
    },
    "Insulation & Drywall": {
        "Insulation": [
            ("Basement walls: min R-20 (NBC 9.36)", "VERIFY"),
            ("Above-grade walls: min R-22 effective", "VERIFY"),
            ("Attic/ceiling: min R-50 (blown or batt)", "VERIFY"),
            ("Rim joist / band joist insulated and sealed", "VERIFY"),
            ("Spray foam at critical air sealing areas", "VERIFY"),
            ("Vapour barrier (6 mil poly) on warm side of insulation", "VERIFY"),
            ("All penetrations sealed (acoustic sealant)", "VERIFY"),
            ("Insulation inspection — passed", "VERIFY"),
            ("Blower door test (if required by program: R-2000, ENERGY STAR)", "VERIFY"),
        ],
        "Air Barrier & Vapour Barrier": [
            ("Continuous air barrier strategy identified", "VERIFY"),
            ("Poly lapped and sealed at all joints", "VERIFY"),
            ("Poly sealed to framing at top and bottom plates", "VERIFY"),
            ("Electrical box vapour barrier boots installed", "VERIFY"),
            ("Window/door rough openings sealed to air barrier", "VERIFY"),
        ],
        "Drywall": [
            ("Drywall thickness per code (1/2\" typical, 5/8\" Type X fire-rated)", "VERIFY"),
            ("Moisture-resistant board in wet areas (greenboard / Densshield)", "VERIFY"),
            ("Drywall screwed at proper spacing (8\" edges, 12\" field)", "VERIFY"),
            ("All joints taped and mudded — Level 4 finish minimum", "VERIFY"),
            ("Corner bead installed straight and clean", "VERIFY"),
            ("No visible screw pops, ridges, or bubbles", "VERIFY"),
            ("Sanding completed — smooth to touch", "VERIFY"),
            ("Drywall dust cleaned before priming", "ACTION"),
        ],
    },
    "Finishing & Closeout": {
        "Interior Finishes": [
            ("Prime coat applied to all drywall surfaces", "VERIFY"),
            ("Paint colours match client selections", "CLIENT"),
            ("Two coats finish paint on walls, one on ceilings", "VERIFY"),
            ("Trim and millwork installed (baseboard, casing, crown)", "VERIFY"),
            ("Interior doors hung, latching, and adjusted", "VERIFY"),
            ("Hardware installed (handles, stops, hinges)", "VERIFY"),
            ("Stair railing / guards installed per code (min 36\" / 42\")", "VERIFY"),
            ("Closet shelving and rods installed", "ACTION"),
        ],
        "Flooring": [
            ("Subfloor cleaned and level before install", "VERIFY"),
            ("Flooring material matches client selection", "CLIENT"),
            ("Transitions between flooring types clean", "VERIFY"),
            ("Tile: layout, grout lines, and slope to drain verified", "VERIFY"),
            ("Hardwood: acclimated, pattern, and expansion gaps", "VERIFY"),
            ("Floor protection in place during remaining work", "ACTION"),
        ],
        "Kitchen & Bath": [
            ("Cabinets level, plumb, and secured to studs", "VERIFY"),
            ("Countertops installed — seams tight, edges smooth", "VERIFY"),
            ("Backsplash installed and grouted", "VERIFY"),
            ("Plumbing fixtures installed and tested (no leaks)", "VERIFY"),
            ("Appliances installed and operational", "VERIFY"),
            ("Tub/shower enclosure sealed — no gaps", "VERIFY"),
            ("Bathroom accessories mounted (towel bars, TP holder)", "ACTION"),
        ],
        "Exterior Finishes": [
            ("Cladding installed per manufacturer specs", "VERIFY"),
            ("Flashing at all transitions (roof-wall, windows, doors)", "VERIFY"),
            ("Soffit and fascia installed, vented properly", "VERIFY"),
            ("Eavestrough and downspouts installed, directed away", "VERIFY"),
            ("Grading slopes away from foundation (min 5% for 2m)", "VERIFY"),
            ("Driveway / walkway poured or paved", "VERIFY"),
            ("Exterior painting / staining completed", "VERIFY"),
            ("Deck / porch constructed per code", "VERIFY"),
        ],
        "Final Inspections & Handover": [
            ("Final building inspection — passed", "VERIFY"),
            ("Occupancy permit obtained", "VERIFY"),
            ("HVAC commissioning and balancing done", "VERIFY"),
            ("All systems tested: electrical, plumbing, HVAC", "VERIFY"),
            ("Deficiency walkthrough with client completed", "CLIENT"),
            ("Deficiency items corrected", "ACTION"),
            ("Homeowner manual / warranty package prepared", "ACTION"),
            ("Keys, remotes, and manuals handed over", "CLIENT"),
            ("Warranty registration completed (Tarion or provincial)", "ACTION"),
            ("Final cleaning done", "ACTION"),
        ],
    },
}
